version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: nome_do_banco_de_dados
            MYSQL_ROOT_PASSWORD: senha_do_banco_de_dados
